name: Deploy página estática do NextJS no Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_homolog:
        description: "Deploy no servidor de homologação"
        type: boolean
        default: false

      redirect_homolog_to_prod:
        description: "Adicionar redirect da homologação para produção"
        type: boolean
        default: false

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: site-build
          path: out/

  deploy-approval-server:
    if: ${{ github.event.inputs.deploy_homolog == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ./out
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to GitHub Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /tmp/deploy_temp && rm -rf /tmp/deploy_temp/*"
          scp -o StrictHostKeyChecking=no -r ./out/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy_temp
      - name: Activate new version on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e

            echo 'Extraindo artifact.tar'
            tar -xf /tmp/deploy_temp/artifact.tar -C /tmp/deploy_temp/
            rm /tmp/deploy_temp/artifact.tar

            echo 'Substituindo versão'
            rsync -a --delete /tmp/deploy_temp/ ${{ secrets.APP_PATH }}/

            echo 'Limpando temporários'
            rm -rf /tmp/deploy_temp
          "
  
  add-redirect:
    if: ${{ github.event.inputs.redirect_homolog_to_prod == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to GitHub Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /tmp/deploy_temp && rm -rf /tmp/deploy_temp/*"
      - name: Add redirect page on homolog server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e

            rm -rf '${{ secrets.APP_PATH }}'/*

            echo '<!DOCTYPE html><html lang=\"pt-BR\"><head><meta charset=\"UTF-8\"><meta http-equiv=\"refresh\" content=\"0; url=https://cbsoft.sbc.org.br/2026\"></head><body><p>Redirecionando para o site oficial...</p></body></html>' > '${{ secrets.APP_PATH }}/index.html'
          "

  deploy-production-server:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install sshpass and openvpn
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openvpn
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ./out
      - name: Create VPN config
        run: |
          echo "${{ secrets.VPN_SBC_OVPN }}" > vpn.ovpn
          chmod 600 vpn.ovpn
      - name: Connect to VPN
        run: |
          echo -e "${{ secrets.VPN_SBC_AUTH_USERNAME }}\n${{ secrets.VPN_SBC_AUTH_PASSWORD }}" > vpn-auth.txt
          chmod 600 vpn-auth.txt

          sudo openvpn \
            --config vpn.ovpn \
            --auth-user-pass vpn-auth.txt \
            --daemon

          echo "Esperando a VPN conectar e o servidor ficar acessível..."
          for i in {1..30}; do
            ping -c1 -W1 ${{ secrets.SSH_SBC_HOSTNAME }} && break
            echo "Aguardando conexão VPN ($i/30)..."
            sleep 2
          done
      - name: Check folder
        run: ls -la ./out
      - name: Deploy to GitHub Server
        run: |
          sshpass -p "${{ secrets.SSH_SBC_PASSWORD }}" ssh -T \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_SBC_USERNAME }}@${{ secrets.SSH_SBC_HOSTNAME }} \
            "mkdir -p ~/tmp/deploy_temp && rm -rf ~/tmp/deploy_temp/*"
          sshpass -p "${{ secrets.SSH_SBC_PASSWORD }}" scp -T \
            -o StrictHostKeyChecking=no \
            -r ./out/. \
            ${{ secrets.SSH_SBC_USERNAME }}@${{ secrets.SSH_SBC_HOSTNAME }}:~/tmp/deploy_temp