name: Deploy página estática do NextJS no Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_homolog:
        description: "Deploy no servidor de homologação"
        type: boolean
        default: false

      redirect_homolog_to_prod:
        description: "Adicionar redirect da homologação para produção"
        type: boolean
        default: false

      deploy_prod:
        description: "Deploy no servidor de produção"
        type: boolean
        default: false

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: site-build
          path: out/

  deploy-approval-server:
    if: ${{ github.event.inputs.deploy_homolog == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: ./out
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to GitHub Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /tmp/deploy_temp && rm -rf /tmp/deploy_temp/*"
          scp -o StrictHostKeyChecking=no -r ./out/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/deploy_temp
      - name: Activate new version on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e

            echo 'Extraindo artifact.tar'
            tar -xf /tmp/deploy_temp/artifact.tar -C /tmp/deploy_temp/
            rm /tmp/deploy_temp/artifact.tar

            echo 'Substituindo versão'
            rsync -a --delete /tmp/deploy_temp/ ${{ secrets.APP_PATH }}/

            echo 'Limpando temporários'
            rm -rf /tmp/deploy_temp
          "
  
  add-redirect:
    if: ${{ github.event.inputs.redirect_homolog_to_prod == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add redirect page on homolog server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            set -e

            mkdir -p ${{ secrets.APP_PATH }}

            cat > ${{ secrets.APP_PATH }}/index.html << 'HTML'
              <!DOCTYPE html>
              <html lang="pt-BR">
                <head>
                  <meta charset="UTF-8">
                  <title>Redirecionando...</title>
                  <meta http-equiv="refresh" content="0; url=https://cbsoft.sbc.org.br/2026">
                </head>
                <body>
                  <p>Redirecionando para o site oficial...</p>
                </body>
                </html>
            HTML

            echo "Redirect aplicado com sucesso"
          "